@Client_HostAddress = http://localhost:5028

### Get counter value
GET {{Client_HostAddress}}/counter/grain-1
Accept: application/json

### Increment counter value
POST {{Client_HostAddress}}/counter/grain-1

